# Generated by Django 5.2.1 on 2025-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_int_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateinterview',
            old_name='candidate_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='candidateinterview',
            old_name='response_time',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='candidateinterview',
            name='question',
        ),
        migrations.RemoveField(
            model_name='candidateinterview',
            name='response',
        ),
        migrations.RemoveField(
            model_name='candidateinterview',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='candidateinterview',
            name='topic',
        ),
        migrations.AlterField(
            model_name='candidateinterview',
            name='feedback',
            field=models.TextField(),
        ),
    ]
