# Generated by Django 5.2.1 on 2025-06-20 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_int_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('response_time', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
